### ISSUE TITLE
Feature : Reverse wrap.

### ISSUE THREAD

**Issue by ghost** [misaelnieto/jquery.wrapSelection#2]
It's not an issue, more a discussion for an extra feature.
I'm using the plugin to highlight text.
I would like to un-highlight it using the same process.
Starting state :
&lt;div&gt;This is a test. This is higlighted.&lt;/div&gt;
Selecting "This is highlighted" to highlight it : 
&lt;div&gt;This is a test. &lt;span class="highlight"&gt;This is higlighted.&lt;/span&gt;&lt;/div&gt;
Switching to UN-highlight mode, selecting "is" to un-highlight it :
&lt;div&gt;This is a test. &lt;span class="highlight"&gt;This&lt;/span&gt;is&lt;span class="highlight"&gt;higlighted.&lt;/span&gt;&lt;/div&gt;

Any tips on how to implement this ?

**Comment by misaelnieto** [comment]
Hi. Sorry to answer soooo late. I haven't worked on this for a looong time, do you still need that extra feature?

**Comment by marechalsamuel** [comment]
Hi. Thank you for replying even late !
But that's fine I figured out something else. :)
Thanks anyway !
